//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExStation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mEntities : DbContext
    {
        public mEntities()
            : base("name=mEntities")
        {
        }
    
        public mEntities(string connection_string)
            : base(connection_string)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<scacclv> scacclv { get; set; }
        public virtual DbSet<sccomp> sccomp { get; set; }
        public virtual DbSet<sccompgroup> sccompgroup { get; set; }
        public virtual DbSet<scuser> scuser { get; set; }
        public virtual DbSet<scusergroup> scusergroup { get; set; }
    }
}
