//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scacclv
    {
        public int id { get; set; }
        public string leveltype { get; set; }
        public string menu { get; set; }
        public string submenu { get; set; }
        public int member_id { get; set; }
        public Nullable<int> scusergroup_id { get; set; }
        public Nullable<int> scuser_id { get; set; }
        public int sccompgroup_id { get; set; }
        public System.DateTime credate { get; set; }
        public Nullable<System.DateTime> chgdate { get; set; }
        public string isread { get; set; }
        public string isadd { get; set; }
        public string isedit { get; set; }
        public string isdelete { get; set; }
        public string isprint { get; set; }
        public string iscancel { get; set; }
        public string isapprove { get; set; }
    
        public virtual member member { get; set; }
        public virtual sccompgroup sccompgroup { get; set; }
        public virtual scuser scuser { get; set; }
        public virtual scusergroup scusergroup { get; set; }
    }
}
