//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sccomp
    {
        public int id { get; set; }
        public string servername { get; set; }
        public string dbname { get; set; }
        public string dbuser { get; set; }
        public string dbpassword { get; set; }
        public string compname { get; set; }
        public System.DateTime credate { get; set; }
        public Nullable<System.DateTime> chgdate { get; set; }
        public int member_id { get; set; }
        public int creby { get; set; }
        public Nullable<int> chgby { get; set; }
        public int sccompgroup_id { get; set; }
    
        public virtual member member { get; set; }
        public virtual scuser scuser { get; set; }
        public virtual scuser scuser1 { get; set; }
        public virtual sccompgroup sccompgroup { get; set; }
    }
}
