//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scuser
    {
        public int id { get; set; }
        public string username { get; set; }
        public string passwordhash { get; set; }
        public int member_id { get; set; }
    
        public virtual member member { get; set; }
    }
}
